<div class="block left-nav">
	<div class="block-title">
	<span><?php echo $this->__('Shop Category') ?></div></span>
	<div class="block-content">
		<ul id="left-nav">
			<style>
				.active1 a{background:none;font-weight:bold;}
				.active2 a{background:none;text-decoration:underline;}
			</style>
			<?php foreach ($this->getStoreCategories() as $_category): ?>
				<?php if ($_category->getIsActive()): ?>
			
					<?php $isactive		= $this->isCategoryActive($_category); ?>
					<?php $hasChildren	= $_category->hasChildren(); ?>
				
					<li class="category <?php if($isactive) echo 'active'; ?>" lang="<?php echo $_category->getId();?>">
						<a href="<?php echo !$hasChildren ? $this->getCategoryUrl($_category) : 'javascript:void(0)'; ?>" >
							<span>
								<?php echo $_category->getName();?>
							</span>
						</a>
						<?php if($isactive) echo " <a class='empty' href='".$this->getCategoryUrl($_category)."'></a>"; ?>
					</li>
					<?php if($hasChildren): ?>
						<ul class="subcategory_<?php echo $_category->getId();?>" style="display:<?php echo $isactive? 'block' : 'none'; ?>;">
							<?php foreach (Mage::getModel('catalog/category')->load($_category->getId())->getChildrenCategories() as $childCategory):?>
								<?php $isactive			= $this->isCategoryActive($childCategory); ?>
								<?php $hasmoreChildren	= $childCategory->hasChildren(); ?>
								
								<li class="category <?php if($isactive) echo 'active1'; ?>" lang="<?php echo $childCategory->getId(); ?>">
									<a href="<?php echo !$hasmoreChildren ? $childCategory->getUrl() : 'javascript:void(0)'; ?>" >
										<?php echo $childCategory->getName(); ?>
									</a>
									<?php if($hasmoreChildren) echo " <a class='empty' href='".$this->getCategoryUrl($childCategory)."'> [+] </a>"; ?>
								</li>
								
								<?php if($hasmoreChildren): ?>
									<ul class="subcategory_<?php echo $childCategory->getId(); ?>" style="display:<?php echo $isactive? 'block' : 'none'; ?>;">
										<?php foreach (Mage::getModel('catalog/category')->load($childCategory->getId())->getChildrenCategories() as $_childCategory):?>
										
											<?php $isactive	= $this->isCategoryActive($_childCategory);?>
											<li class="category <?php if($isactive) echo 'active2';?>">
												<a href="<?php echo $_childCategory->getUrl(); ?>" >
													<?php echo $_childCategory->getName(); ?>
												</a>
											</li>
										<?php endforeach; ?>
									</ul>
								<?php endif ?>
							
							<?php endforeach;?>
						</ul>
					<?php endif ?>
				<?php endif ?>
			<?php endforeach ?>
		</ul>
	</div>
</div>
